name: buscando_minas
description: "The Best Minesweeper who you would see in your life, dude"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/
